### Login
POST http://localhost:3000/admin/login
Content-Type: application/json

{
  "username": "f4nguyen",
  "password": "04258245"
}

### Refresh Database
POST http://localhost:3000/admin/refresh
Content-Type: application/json

{
  "username": "f4nguyen",
  "password": "04258245"
}

### Drop Tables
POST http://localhost:3000/admin/drop-tables
Content-Type: application/json

{
  "username": "f4nguyen",
  "password": "04258245"
}

### Create Tables
POST http://localhost:3000/admin/create-tables
Content-Type: application/json

{
  "username": "f4nguyen",
  "password": "04258245"
}
### Populate Tables
POST http://localhost:3000/admin/populate-tables
Content-Type: application/json

{
  "username": "f4nguyen",
  "password": "04258245"
}
### Query
POST http://localhost:3000/admin/query
Content-Type: application/json

{
  "username": "f4nguyen",
  "password": "04258245",
  "choice": 1
}
